const API_REQUEST_SUCCESS = "OK"
const NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
const AUTHENTICATED = "AUTHENTICATED"
const EMPTY_FIELDS_ERROR = "Please fill out empty fields"

export { API_REQUEST_SUCCESS, EMPTY_FIELDS_ERROR, NOT_AUTHENTICATED, AUTHENTICATED }