"""Initial migration from SQLite

Revision ID: 9d8e1c2036fb
Revises: 
Create Date: 2025-05-03 09:43:39.367696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d8e1c2036fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('tracker_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('calorie')

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_goal', sa.Integer(), nullable=True))
        batch_op.drop_constraint('userinfo_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint('workout_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('workout_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('userinfo_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('streak_goal')

    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tracker_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('barcode')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
