repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        name: Ruff Lint and Fix Imports
        args: [--select, I, --fix]
      - id: ruff-format
        name: Ruff Format Code
