import { StyleSheet } from "react-native";
import { background_color } from "../../../GlobalStyles";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: background_color,
        padding: 20,
        alignItems: 'center',
    },
    header: {
        width: '100%',
        paddingVertical: 25,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    headerText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
    },
    contentContainer: {
        width: '100%',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 3,
    },
    dataLabel: {
        fontSize: 20,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 15,
        marginTop: 15,
    },
    dataValue: {
        fontWeight: 'normal',
    },
    bodyDataContainer: {
        width: '100%',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 16,
        padding: 15,
        paddingHorizontal: 20,
        textAlignVertical: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 3,
        marginVertical: 10,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dataValueInput: {
        borderBottomWidth: 1,
        borderBottomColor: '#fff',
        color: '#fff',
        padding: 2,
        minWidth: 80,
        marginRight: 10,
    },
    rightGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    dataValue: {
        color: '#fff',
        fontSize: 20,
        textAlign: 'right',
        marginTop: 15,
        marginRight: 6,
    },
    dataValueInput: {
        borderBottomWidth: 1,
        borderBottomColor: '#fff',
        color: '#fff',
        padding: 2,
        minWidth: 80,
        textAlign: 'right',
        marginRight: 6,
    },
    saveButton: {
        position: 'absolute',
        bottom: 20,
        alignSelf: 'center',
        backgroundColor: '#CC0033',
        paddingHorizontal: 30,
        paddingVertical: 12,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    addButton: {
        position: 'absolute',
        bottom: 110,
        left: 20,
        right: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#CC0033',
        padding: 20,
        paddingVertical: 25,
        borderRadius: 8,
        shadowColor: 'black',
        shadowOffset: { height: 1, width: 1 },
        shadowOpacity: 1,
        shadowRadius: 3,
        elevation: 2,
        borderRadius: 16,
    },
    addButtonText: {
        color: 'white',
        marginLeft: 10,
        fontWeight: 'bold',
    },
    picker: {
        width: 200,
        color: 'white',
    },
    pickerItem: {
        color: 'white',
    },
});
