name: CI - Flask Backend

on:
  push:
    branches: [main, dev, 'SPR6*']
  pull_request:
    branches: [main, dev, 'SPR6*']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flask-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Fix import order with Ruff
        run: pipenv run ruff check --select I --fix .

      - name: Format code with Ruff
        run: pipenv run ruff format .

      - name: Run Unit Tests
        run: pipenv run pytest
